README.md, collectors/monitoring_collector.go, stackdriver_exporter.go
This allows offsetting the metrics interval into the past. This is useful to e.g. fetch 1 minutes worth of metrics from 3 minutes ago, to avoid double-counting and latency issues. See #12 for details.
=> Added -monitoring.metrics-offset flag

README.md, collectors/monitoring_collector.go
A Counter is defined as a cumulative metric that only ever goes up. The DELTA value could go up or down depending on the minute of time and what is measured.
Tested this on our live instance and switching this without changing the name doesn't seem to break anything in Prometheus.
=> Switch DELTA to gauge from counter

collectors/monitoring_collector.go
By multiplying the mean * count we can get back to the sum.
=> Stackdriver doesn't provide a sum, but it does provide a mean and a count.

collectors/monitoring_collector.go
It turns out that even a single nanosecond difference between starttime and endtime results in an additional block of timeseries data to be loaded.
As it was implemented, the `monitoring.metrics-interval` between starttime and endtime would be a tiny bit wider than requested.
It seems a minor thing, but it causes the API to return another block of data (another minute's worth of data).
When requesting data via the API monitoring, it uses the `endtime` as the starting point for the range of data to be returned (mandatory field). It then works its way backwards until it fulfils the provided `starttime` in the API call (optional field).
It only stops when the `starttime` of the block of data is of an earlier or equals date to the `starttime` specified in the API call. Remember that the data …
=> Align starttime and endtime to be based on the same time.Now() call

stackdriver_exporter.go
If no credentials supplied stackdriver_exporter binary goes segfaulted:
```
oring.metrics-type-prefixes container.googleapis.com --stackdriver.http-timeout=10s
INFO[0000] Starting stackdriver_exporter (version=0.5.1, branch=master, revision=c36707967ebec2fb8977a54003797e5148c24936)  source="stackdriver_exporter.go:122"
INFO[0000] Build context (go=go1.10.5, user=root@857d0832fe06, date=20181119-16:33:41)  source="stackdriver_exporter.go:123"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7b5e47]
goroutine 1 [running]:
main.createMonitoringService(0xc420049f38, 0x2, 0x2)
/go/src/github.com/frodenas/stackdriver_exporter/stackdriver_exporter.go:84 +0xa7
main.main() …
```
=> Fix segmentation fault on missing credentials

collectors/monitoring_collector.go, stackdriver_exporter.go
Stackdriver allows delegation of multiple projects to "main" one. This is very useful to create inter-project dashbords, but also it delegates all metrics to single project and could lead to big amounts of series. I've added optional flag `monitoring.drop-delegated-projects` which allows one to disable collection of these metrics. It's useful to split stackdriver-exporter instances per-project
and still be able to fetch metrics from main one.
Another option is to have empty main project only to delegate monitoring and not to fetch metrics from.
=> Add option to drop metrics from delegated projects

collectors/monitoring_collector.go
Fixes #48 
The approach taken here is to deduplicate metric descriptors based on `descriptor.Type` field, so we fetch metrics from a specific descriptor only once.
Please, review whether this approach is correct or there is a better way of doing it.
=> Ensure metrics are fetched once for each metric descriptor

.circleci/config.yml, .golangci.yml, collectors/collectors_suite_test.go, collectors/fnv.go, collectors/monitoring_collector.go, collectors/monitoring_metrics.go, scripts/errcheck_excludes.txt, stackdriver_exporter.go, utils/test_matchers/prometheus_metric_matcher.go, utils/test_matchers/prometheus_metric_matcher_test.go, utils/test_matchers/test_matchers_suite_test.go, utils/utils.go, utils/utils_suite_test.go, utils/utils_test.go
Needs `build` name for requirements matching.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Fix CircleCI publish master

.promu.yml, Dockerfile, Makefile, README.md
Update Dockerfile and Makefile to support multi-arch images.
* Cleanup promu config.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Use multi-arch Dockerfile

CHANGELOG.md, README.md, collectors/monitoring_collector.go, stackdriver_exporter.go
Add URL param `collect[]` to allow requesting a filterd list of metrics.
Fixes: https://github.com/prometheus-community/stackdriver_exporter/issues/61
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Add metrics prefix collect URL param

collectors/monitoring_collector.go
Exit on any failure to collect metrics.  This will give
`stackdriver_exporter` a chance to start over and perhaps recover from
transient errors.  For example: if it's Google credentials have expired
and have been replaced, it can restart to try to load up new ones.
Closes #66
=> Treat failure to collect metric as fatal

README.md, stackdriver_exporter.go
Don't use `[]` in the collect param name, avoids Prometheus relabeling
issue with `__param_collect[]` being "invalid" as a target label.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Fix collect param name

CHANGELOG.md, collectors/monitoring_collector.go
Reverts PR #83 (see discussion in the issue for more information).
=> Do not treat failure to collect metrics as fatal

README.md, stackdriver_exporter.go
Fixes issue #55  
Is a more up-to-date version of pull request #60
Signed-off-by: Ross Murray <rossmichaelm@gmail.com>
=> add support for multiple google project IDs

collectors/monitoring_collector.go
Fixes #95 @SuperQ 
The copy function takes args (dst, src), so it was copying the empty buckets into the explicit boundaries.
=> fix custom bucket boundaries

README.md, collectors/monitoring_collector.go, utils/utils.go
Add `monitoring.filters` flag
Allow more granularity when requesting for time series list by letting developers refine their metrics by using Filter objects that Google provides. 
```
Filter objects: project, group.id, resource.type, resource.labels.[KEY], metric.type, metric.labels.[KEY]
```
https://cloud.google.com/monitoring/api/v3/filters
```
go run stackdriver_exporter.go \
--google.project-id=my-project \
--monitoring.metrics-type-prefixes='pubsub.googleapis.com/subscription/num_undelivered_messages,redis.googleapis.com' \
--monitoring.filters='pubsub.googleapis.com/subscription:resource.labels.subscription_id=monitoring.regex.full_match("us-west4.*my-team.*")'
```
=> add monitoring.filters flag

README.md
The two permissions previously listed are not enough to scrape the metrics. While we can build a detailed list of all the needed permissions, I think specifying just the role could be enough. The permission list might change in the future, and it isn't easy to maintain. Reasonably, the role will be updated by Google if additional permissions would be required.
cc @SuperQ
=> Update IAM permissions in README.md

stackdriver_exporter.go
Otherwise all exporter metrics will be re-created on every scrape. Based on the same pattern as node_exporter.
Resolves #108, resolves #109
When using the `collect` query parameter, it will still create everything on the fly, I don't have any knowledge in how that setting is supposed to work, if that is expected behavior, or if there is still a bug there, but node_exporter seems to handle that case in the same way.
=> setup exporter metrics only once when we can

CHANGELOG.md, README.md, collectors/monitoring_collector.go, manifest.yml, stackdriver_exporter.go
Drop ENV vars from flags as this is non-standard in the Prometheus
ecosystem.
* Drop extraneous manifest.yml.
Signed-off-by: SuperQ <superq@gmail.com>
=> Cleanup non-standard ENV var setup

collectors/monitoring_collector.go
Metric like `istio.io/control` were failing because `mesh_id` and some other labels were added multiple times
=> Fixes suspected duplicate label panic for some GCP metric

README.md
In https://github.com/prometheus-community/stackdriver_exporter/pull/133 filtering was added but the example in the README was still referencing an old style arg.
=> Fix the example filter arg

README.md, collectors/monitoring_collector.go
We noticed that with `metrics-ingest-delay` flag set the exporter fails to apply the time offset as expected, despite what the debug log prints. The root cause appears to be failing to assign back the start and end times back to the original target as indicated in my PR below. 
I've dropped the fmt.Printf statements that allowed us to locate the bug, but feel free to revert my second commit locally to reproduce the issue. You might need to change the IF conditional from Stored bytes, a BigQuery metric, to another similar metric depending on what project you use for testing and what APIs you have available there.
I also added the feature to the README since it seems to be good to go otherwise!
=> Metrics-ingest-delay bugfix

collectors/monitoring_collector.go
Doing some trials with the exporter, I found a data race condition in the go-routines launched by each `metricDescriptorsFunction` when about to pull time series.
The raw stacktrace goes as follows:
```
==================
WARNING: DATA RACE
Write at 0x00c00000f7b8 by goroutine 104:
github.com/prometheus-community/stackdriver_exporter/collectors.(*MonitoringCollector).reportMonitoringMetrics.func1.1()
/Users/pablo/work/stackdriver_exporter/collectors/monitoring_collector.go:245 +0x834
github.com/prometheus-community/stackdriver_exporter/collectors.(*MonitoringCollector).reportMonitoringMetrics.func1.2()
/Users/pablo/work/stackdriver_exporter/collectors/monitoring_collector.go:283 +0x58
Previous read at 0x00c00000f7b8 by goroutine 41: …
```
=> Fix data race on metricDescriptorsFunction start and end times

README.md
This PR fixes the argument `--google.project-id` in the README. It should contain an equal sign between the flag an the value, as tested in the container for `v0.12.0`.
=> Fix README call with --google.project-id

CHANGELOG.md, stackdriver_exporter.go
@SuperQ 
This PR introduces a new flag to make it possible to serve the go runtime metrics on a seperate endpoint. The way we are orchestrating the deployment of the exporter (multiple k8s deployments), this flag will effectively halve our stackdriver API calls. 
Manual testing done:
* With and without flag.
* Launch process locally with one of our GCP projects.
* Verify endpoint(s) contain what they should.
=> Make it possible to support runtime metrics on a seperate path

collectors/monitoring_collector.go, collectors/monitoring_metrics.go
Use `const` to define namespace and subsystem parts to avoid typos.
Signed-off-by: SuperQ <superq@gmail.com>
=> Refactor metric naming

.gitignore, README.md
Adding some badges to `README.md` with project information:
[![golangci-lint](https://github.com/prometheus-community/stackdriver_exporter/actions/workflows/golangci-lint.yml/badge.svg)](https://github.com/prometheus-community/stackdriver_exporter/actions/workflows/golangci-lint.yml)
[![Go Report Card](https://goreportcard.com/badge/github.com/prometheus-community/stackdriver_exporter)](https://goreportcard.com/report/github.com/prometheus-community/stackdriver_exporter)
[![GoDoc](https://pkg.go.dev/badge/github.com/prometheus-community/stackdriver_exporter?status.svg)](https://pkg.go.dev/github.com/prometheus-community/stackdriver_exporter?tab=doc)
[![Release](https://img.shields.io/github/v/release/prometheus-community/stackdriver_exporter)](https://github.com/prometheus-community/stackd …
=> Add status badges to README

README.md
It might be obvious to those "in the know" that the prometheus-community has a Helm chart for this exporter, but for the unitialized, the standard method for determining whether there is a Helm chart is to check to the README of the given project.\
Seriously, my organization has run a custom Helm chart for years before I found out there is an upstream one while refactoring ours. :smile:
=> Mention community Helm chart in README

collectors/cache.go, collectors/cache_test.go, collectors/monitoring_collector.go, collectors/monitoring_collector_test.go, stackdriver_exporter.go
See issue #217
This commit introduces a simple prefix -> []descriptor cache. If the prefix isn't in the cache the original page based lookup is performed and at the end of it the cache is updated. If it does exist in the cache the cached value is used.
No attempt is made to prevent two routines from updating the cache concurrently. If two concurrent requests see an expired cache entry they'll both do the ListDescriptor call and update the cache. Doing this keeps the cache simple and doesn't block one request on the other. This situation will also be rare in practice, as there is usually only one or two prometheuses scraping.
The cache itself comes in 3 flavors:
- noop, does nothing
- descriptorCache, caches all descriptors
- googleDescriptorCache, caches only descriptors of google metrics …
=> cache descriptors to reduce API calls

CONTRIBUTING.md
Updates the CONTRIBUTING.md file to have the proper command to build and run `stackdriver_exporter`.
=> fix(docs): Update CONTRIBUTING.md to reflect build process

README.md, stackdriver_exporter.go
Hey @SuperQ , discovered that my recent contribution in #164 breaks the delta metrics aggregation feature 😞 , so I suggest we revert for now.
Full explanation is in https://github.com/prometheus-community/stackdriver_exporter/issues/315.
=> Revert "Add feature to filter project ID at call-time (#164)"

collectors/monitoring_metrics.go, delta/histogram.go, delta/histogram_test.go
The current implementation is not merging the histogram correctly. The sum is calculated as follow:
count * (existingMean + currentMean) / 2
Now let's say that the existing histogram has a count of 1000 and an existing mean of 10000, the incoming histogram has a count of 100 and a mean of 1000.
newCount = 1000 + 100 = 1100
newMean = (10000 + 1000) / 2 = 5500
newSum = 1100 * newMean = 6_050_000
Now the next incoming histogram has a count of 1000 and an existing mean of 100:
newCount = 1100 + 1000 = 2100
newMean = (5500 +100) / 2 = 2800
newSum = 2100 * 2800 = 5_880_000
By definition, the sum of the histogram is supposed to behave like a counter (A counter is a cumulative metric that represents a single [monotonically increasing counter](https://en.wikipedia.org/wiki/Monotonic_function) …
=> [Bugfix]: Fix histogram merge 

README.md, collectors/monitoring_collector.go, stackdriver_exporter.go, utils/utils.go
Adjusts the way `monitoring.filters` are documented and applied. 
Similar to #165, I found it hard to use the filters initially so hopefully more detailed docs can help. Especially related to the fact that the `monitoring.filters` flag should be specified multiple times vs comma delimited like other multi-valued params.
This also adjusts the way the filters are applied to be based on prefix vs contains, https://github.com/prometheus-community/stackdriver_exporter/pull/198/commits/507f6b3119310e14e3a62e66b30100f899e00de0. I think the original contains implementation made it hard to define what exactly belongs in the first section of the extra_filters. Forcing it to be a prefix makes it a lot more concrete.
=> Add more info about filters to docs and rename struct fields

stackdriver_exporter.go, stackdriver_exporter_test.go
When more than one prefix matches the same metric descriptor, this will throw the error `collected metric xxx was collected before with the same name and label values`.
For example, using the metric type prefixes
`foo.googleapis.com/bar (a prefix)`
and
`foo.googleapis.com/bar/baz (a metric)`
will result in an error because both match the metric
`foo.googleapis.com/bar/baz`.
Further, using the metric type prefixes
`foo.googleapis.com/bar/baz (a metric)`
and
`foo.googleapis.com/bar/baz_count (a metric)`
will result in an error because both match the metric
`foo.googleapis.com/bar/baz_count`.
While the first pitfall could be expected by the user, the latter will come as a complete surprise to anyone who is not aware that stackdriver-exporter internally uses an MQL query in the form of …
=> Sanitize metric type prefixes

collectors/monitoring_collector.go
When exporting metrics from multiple projects at once, it's useful to know which of the projects is generating metrics errors.
Heya @SuperQ , tagging you per the contributors guide. Mind taking a look when you get a minute?
=> Add project IDs to error logs

stackdriver_exporter.go, stackdriver_exporter_test.go
This changes the `?collect` parameter filter to allow more specific prefixes than those setup in the metrics-prefixes.
Example use cases:
1. I have the `redis.googleapis.com/stats/memory/usage_ratio` prefix set in the `?collect` config of dozens of projects. 
Now, I'd like to enable the `redis.googleapis.com/stats/memory/usage` metric in the stackdriver_exporter metric prefixes, but since it conflicts with the more-specific `redis.googleapis.com/stats/memory/usage_ratio` metric name, the exporter will stop accepting the `?collect` param I've set in other configurations.
2. I want to whitelist all `redis.googleapis.com` metrics, but only collect 1 or 2 metrics with `?collect`. Currently, the prefixes have to be exact matches so this is not possible without the proposed change.
---
To test: …
=> feat: support more specific prefixes in ?collect parameter

stackdriver_exporter.go
Fixup warning:
> S1005: unnecessary assignment to the blank identifier (gosimple)
=> Fixup linter warning
